#!/bin/zsh
# Installed at ~/.zshrc by the `rcfiles` action, which names no file at all:
# it installs whatever is in this directory, dotted.

source ~/.zshenv
source ~/.config/zsh/aliases.zsh

setopt hist_ignore_dups
setopt share_history

HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history

PROMPT='%F{cyan}%~%f %# '
